export const options = [
	{ label: '3M India Ltd.', value: '3MINDIA.NS' },
	{ label: 'ABB India Ltd.', value: 'ABB.NS' },
	{ label: 'ACC Ltd.', value: 'ACC.NS' },
	{ label: 'AIA Engineering Ltd.', value: 'AIAENG.NS' },
	{ label: 'APL Apollo Tubes Ltd.', value: 'APLAPOLLO.NS' },
	{ label: 'AU Small Finance Bank Ltd.', value: 'AUBANK.NS' },
	{ label: 'Aarti Drugs Ltd.', value: 'AARTIDRUGS.NS' },
	{ label: 'Aavas Financiers Ltd.', value: 'AAVAS.NS' },
	{ label: 'Abbott India Ltd.', value: 'ABBOTINDIA.NS' },
	{ label: 'Adani Enterprises Ltd.', value: 'ADANIENT.NS' },
	{ label: 'Adani Green Energy Ltd.', value: 'ADANIGREEN.NS' },
	{ label: 'Adani Ports and Special Economic Zone Ltd.', value: 'ADANIPORTS.NS' },
	{ label: 'Adani Total Gas Ltd.', value: 'ATGL.NS' },
	{ label: 'Adani Transmission Ltd.', value: 'ADANITRANS.NS' },
	{ label: 'Aditya Birla Capital Ltd.', value: 'ABCAPITAL.NS' },
	{ label: 'Aditya Birla Fashion and Retail Ltd.', value: 'ABFRL.NS' },
	{ label: 'Aditya Birla Sun Life AMC Ltd.', value: 'ABSLAMC.NS' },
	{ label: 'Advanced Enzyme Tech Ltd.', value: 'ADVENZYMES.NS' },
	{ label: 'Aegis Logistics Ltd.', value: 'AEGISCHEM.NS' },
	{ label: 'Affle (India) Ltd.', value: 'AFFLE.NS' },
	{ label: 'Ajanta Pharmaceuticals Ltd.', value: 'AJANTPHARM.NS' },
	{ label: 'Alembic Pharmaceuticals Ltd.', value: 'APLLTD.NS' },
	{ label: 'Alkem Laboratories Ltd.', value: 'ALKEM.NS' },
	{ label: 'Alkyl Amines Chemicals Ltd.', value: 'ALKYLAMINE.NS' },
	{ label: 'Allcargo Logistics Ltd.', value: 'ALLCARGO.NS' },
	{ label: 'Alok Industries Ltd.', value: 'ALOKINDS.NS' },
	{ label: 'Amara Raja Batteries Ltd.', value: 'AMARAJABAT.NS' },
	{ label: 'Amber Enterprises India Ltd.', value: 'AMBER.NS' },
	{ label: 'Ambuja Cements Ltd.', value: 'AMBUJACEM.NS' },
	{ label: 'Angel One Ltd.', value: 'ANGELONE.NS' },
	{ label: 'Anupam Rasayan India Ltd.', value: 'ANURAS.NS' },
	{ label: 'Apollo Hospitals Enterprise Ltd.', value: 'APOLLOHOSP.NS' },
	{ label: 'Apollo Tyres Ltd.', value: 'APOLLOTYRE.NS' },
	{ label: 'Aptus Value Housing Finance India Ltd.', value: 'APTUS.NS' },
	{ label: 'Asahi India Glass Ltd.', value: 'ASAHIINDIA.NS' },
	{ label: 'Ashok Leyland Ltd.', value: 'ASHOKLEY.NS' },
	{ label: 'Asian Paints Ltd.', value: 'ASIANPAINT.NS' },
	{ label: 'Aster DM Healthcare Ltd.', value: 'ASTERDM.NS' },
	{ label: 'AstraZenca Pharma India Ltd.', value: 'ASTRAZEN.NS' },
	{ label: 'Astral Ltd.', value: 'ASTRAL.NS' },
	{ label: 'Atul Ltd.', value: 'ATUL.NS' },
	{ label: 'Aurobindo Pharma Ltd.', value: 'AUROPHARMA.NS' },
	{ label: 'Avanti Feeds Ltd.', value: 'AVANTIFEED.NS' },
	{ label: 'Avenue Supermarts Ltd.', value: 'DMART.NS' },
	{ label: 'Axis Bank Ltd.', value: 'AXISBANK.NS' },
	{ label: 'BASF India Ltd.', value: 'BASF.NS' },
	{ label: 'BSE Ltd.', value: 'BSE.NS' },
	{ label: 'Bajaj Auto Ltd.', value: 'BAJAJ-AUTO.NS' },
	{ label: 'Bajaj Electricals Ltd', value: 'BAJAJELEC.NS' },
	{ label: 'Bajaj Finance Ltd.', value: 'BAJFINANCE.NS' },
	{ label: 'Bajaj Finserv Ltd.', value: 'BAJAJFINSV.NS' },
	{ label: 'Bajaj Holdings & Investment Ltd.', value: 'BAJAJHLDNG.NS' },
	{ label: 'Balaji Amines Ltd.', value: 'BALAMINES.NS' },
	{ label: 'Balkrishna Industries Ltd.', value: 'BALKRISIND.NS' },
	{ label: 'Balrampur Chini Mills Ltd.', value: 'BALRAMCHIN.NS' },
	{ label: 'Bandhan Bank Ltd.', value: 'BANDHANBNK.NS' },
	{ label: 'Bank of Baroda', value: 'BANKBARODA.NS' },
	{ label: 'Bank of India', value: 'BANKINDIA.NS' },
	{ label: 'Bank of Maharashtra', value: 'MAHABANK.NS' },
	{ label: 'Bata India Ltd.', value: 'BATAINDIA.NS' },
	{ label: 'Bayer Cropscience Ltd.', value: 'BAYERCROP.NS' },
	{ label: 'Berger Paints India Ltd.', value: 'BERGEPAINT.NS' },
	{ label: 'Bharat Dynamics Ltd.', value: 'BDL.NS' },
	{ label: 'Bharat Electronics Ltd.', value: 'BEL.NS' },
	{ label: 'Bharat Forge Ltd.', value: 'BHARATFORG.NS' },
	{ label: 'Bharat Heavy Electricals Ltd.', value: 'BHEL.NS' },
	{ label: 'Bharat Petroleum Corporation Ltd.', value: 'BPCL.NS' },
	{ label: 'Bharti Airtel Ltd.', value: 'BHARTIARTL.NS' },
	{ label: 'Biocon Ltd.', value: 'BIOCON.NS' },
	{ label: 'Birla Corporation Ltd.', value: 'BIRLACORPN.NS' },
	{ label: 'Birlasoft Ltd.', value: 'BSOFT.NS' },
	{ label: 'Blue Dart Express Ltd.', value: 'BLUEDART.NS' },
	{ label: 'Blue Star Ltd.', value: 'BLUESTARCO.NS' },
	{ label: 'Bombay Burmah Trading Corporation Ltd.', value: 'BBTC.NS' },
	{ label: 'Borosil Renewables Ltd.', value: 'BORORENEW.NS' },
	{ label: 'Bosch Ltd.', value: 'BOSCHLTD.NS' },
	{ label: 'Brigade Enterprises Ltd.', value: 'BRIGADE.NS' },
	{ label: 'Brightcom Group Ltd.', value: 'BCG.NS' },
	{ label: 'Britannia Industries Ltd.', value: 'BRITANNIA.NS' },
	{ label: 'C.E. Info Systems Ltd.', value: 'MAPMYINDIA.NS' },
	{ label: 'CCL Products (I) Ltd.', value: 'CCL.NS' },
	{ label: 'CESC Ltd.', value: 'CESC.NS' },
	{ label: 'CG Power and Industrial Solutions Ltd.', value: 'CGPOWER.NS' },
	{ label: 'CRISIL Ltd.', value: 'CRISIL.NS' },
	{ label: 'CSB Bank Ltd.', value: 'CSBBANK.NS' },
	{ label: 'Campus Activewear Ltd.', value: 'CAMPUS.NS' },
	{ label: 'Can Fin Homes Ltd.', value: 'CANFINHOME.NS' },
	{ label: 'Canara Bank', value: 'CANBK.NS' },
	{ label: 'Caplin Point Laboratories Ltd.', value: 'CAPLIPOINT.NS' },
	{ label: 'Capri Global Capital Ltd.', value: 'CGCL.NS' },
	{ label: 'Carborundum Universal Ltd.', value: 'CARBORUNIV.NS' },
	{ label: 'Castrol India Ltd.', value: 'CASTROLIND.NS' },
	{ label: 'Ceat Ltd.', value: 'CEATLTD.NS' },
	{ label: 'Central Bank of India', value: 'CENTRALBK.NS' },
	{ label: 'Central Depository Services (India) Ltd.', value: 'CDSL.NS' },
	{ label: 'Century Plyboards (India) Ltd.', value: 'CENTURYPLY.NS' },
	{ label: 'Century Textile & Industries Ltd.', value: 'CENTURYTEX.NS' },
	{ label: 'Cera Sanitaryware Ltd', value: 'CERA.NS' },
	{ label: 'Chalet Hotels Ltd.', value: 'CHALET.NS' },
	{ label: 'Chambal Fertilizers & Chemicals Ltd.', value: 'CHAMBLFERT.NS' },
	{ label: 'Chemplast Sanmar Ltd.', value: 'CHEMPLASTS.NS' },
	{ label: 'Cholamandalam Financial Holdings Ltd.', value: 'CHOLAHLDNG.NS' },
	{ label: 'Cholamandalam Investment and Finance Company Ltd.', value: 'CHOLAFIN.NS' },
	{ label: 'Cipla Ltd.', value: 'CIPLA.NS' },
	{ label: 'City Union Bank Ltd.', value: 'CUB.NS' },
	{ label: 'Clean Science and Technology Ltd.', value: 'CLEAN.NS' },
	{ label: 'Coal India Ltd.', value: 'COALINDIA.NS' },
	{ label: 'Cochin Shipyard Ltd.', value: 'COCHINSHIP.NS' },
	{ label: 'Coforge Ltd.', value: 'COFORGE.NS' },
	{ label: 'Colgate Palmolive (India) Ltd.', value: 'COLPAL.NS' },
	{ label: 'Computer Age Management Services Ltd.', value: 'CAMS.NS' },
	{ label: 'Container Corporation of India Ltd.', value: 'CONCOR.NS' },
	{ label: 'Coromandel International Ltd.', value: 'COROMANDEL.NS' },
	{ label: 'CreditAccess Grameen Ltd.', value: 'CREDITACC.NS' },
	{ label: 'Crompton Greaves Consumer Electricals Ltd.', value: 'CROMPTON.NS' },
	{ label: 'Cummins India Ltd.', value: 'CUMMINSIND.NS' },
	{ label: 'Cyient Ltd.', value: 'CYIENT.NS' },
	{ label: 'DCM Shriram Ltd.', value: 'DCMSHRIRAM.NS' },
	{ label: 'DLF Ltd.', value: 'DLF.NS' },
	{ label: 'Dabur India Ltd.', value: 'DABUR.NS' },
	{ label: 'Dalmia Bharat Ltd.', value: 'DALBHARAT.NS' },
	{ label: 'Deepak Nitrite Ltd.', value: 'DEEPAKNTR.NS' },
	{ label: 'Delhivery Ltd.', value: 'DELHIVERY.NS' },
	{ label: 'Delta Corp Ltd.', value: 'DELTACORP.NS' },
	{ label: 'Devyani International Ltd.', value: 'DEVYANI.NS' },
	{ label: 'Dhani Services Ltd.', value: 'DHANI.NS' },
	{ label: 'Dilip Buildcon Ltd.', value: 'DBL.NS' },
	{ label: "Divi's Laboratories Ltd.", value: 'DIVISLAB.NS' },
	{ label: 'Dixon Technologies (India) Ltd.', value: 'DIXON.NS' },
	{ label: 'Dr. Lal Path Labs Ltd.', value: 'LALPATHLAB.NS' },
	{ label: "Dr. Reddy's Laboratories Ltd.", value: 'DRREDDY.NS' },
	{ label: 'E.I.D. Parry (India) Ltd.', value: 'EIDPARRY.NS' },
	{ label: 'EIH Ltd.', value: 'EIHOTEL.NS' },
	{ label: 'EPL Ltd.', value: 'EPL.NS' },
	{ label: 'Easy Trip Planners Ltd.', value: 'EASEMYTRIP.NS' },
	{ label: 'Edelweiss Financial Services Ltd.', value: 'EDELWEISS.NS' },
	{ label: 'Eicher Motors Ltd.', value: 'EICHERMOT.NS' },
	{ label: 'Elgi Equipments Ltd.', value: 'ELGIEQUIP.NS' },
	{ label: 'Emami Ltd.', value: 'EMAMILTD.NS' },
	{ label: 'Endurance Technologies Ltd.', value: 'ENDURANCE.NS' },
	{ label: 'Engineers India Ltd.', value: 'ENGINERSIN.NS' },
	{ label: 'Equitas Holdings Ltd.', value: 'EQUITAS.NS' },
	{ label: 'Equitas Small Finance Bank Ltd.', value: 'EQUITASBNK.NS' },
	{ label: 'Eris Lifesciences Ltd.', value: 'ERIS.NS' },
	{ label: 'Escorts Kubota Ltd.', value: 'ESCORTS.NS' },
	{ label: 'Exide Industries Ltd.', value: 'EXIDEIND.NS' },
	{ label: 'FDC Ltd.', value: 'FDC.NS' },
	{ label: 'FSN E-Commerce Ventures Ltd.', value: 'NYKAA.NS' },
	{ label: 'Federal Bank Ltd.', value: 'FEDERALBNK.NS' },
	{ label: 'Fertilisers and Chemicals Travancore Ltd.', value: 'FACT.NS' },
	{ label: 'Fine Organic Industries Ltd.', value: 'FINEORG.NS' },
	{ label: 'Finolex Cables Ltd.', value: 'FINCABLES.NS' },
	{ label: 'Finolex Industries Ltd.', value: 'FINPIPE.NS' },
	{ label: 'Firstsource Solutions Ltd.', value: 'FSL.NS' },
	{ label: 'Fortis Healthcare Ltd.', value: 'FORTIS.NS' },
	{ label: 'G R Infraprojects Ltd.', value: 'GRINFRA.NS' },
	{ label: 'GAIL (India) Ltd.', value: 'GAIL.NS' },
	{ label: 'GMM Pfaudler Ltd.', value: 'GMMPFAUDLR.NS' },
	{ label: 'GMR Infrastructure Ltd.', value: 'GMRINFRA.NS' },
	{ label: 'Galaxy Surfactants Ltd.', value: 'GALAXYSURF.NS' },
	{ label: 'Garware Technical Fibres Ltd.', value: 'GARFIBRES.NS' },
	{ label: 'General Insurance Corporation of India', value: 'GICRE.NS' },
	{ label: 'Gland Pharma Ltd.', value: 'GLAND.NS' },
	{ label: 'Glaxosmithkline Pharmaceuticals Ltd.', value: 'GLAXO.NS' },
	{ label: 'Glenmark Life Sciences Ltd.', value: 'GLS.NS' },
	{ label: 'Glenmark Pharmaceuticals Ltd.', value: 'GLENMARK.NS' },
	{ label: 'Go Fashion (India) Ltd.', value: 'GOCOLORS.NS' },
	{ label: 'Godfrey Phillips India Ltd.', value: 'GODFRYPHLP.NS' },
	{ label: 'Godrej Agrovet Ltd.', value: 'GODREJAGRO.NS' },
	{ label: 'Godrej Consumer Products Ltd.', value: 'GODREJCP.NS' },
	{ label: 'Godrej Industries Ltd.', value: 'GODREJIND.NS' },
	{ label: 'Godrej Properties Ltd.', value: 'GODREJPROP.NS' },
	{ label: 'Granules India Ltd.', value: 'GRANULES.NS' },
	{ label: 'Graphite India Ltd.', value: 'GRAPHITE.NS' },
	{ label: 'Grasim Industries Ltd.', value: 'GRASIM.NS' },
	{ label: 'Great Eastern Shipping Co. Ltd.', value: 'GESHIP.NS' },
	{ label: 'Grindwell Norton Ltd.', value: 'GRINDWELL.NS' },
	{ label: 'Gujarat Alkalies & Chemicals Ltd.', value: 'GUJALKALI.NS' },
	{ label: 'Gujarat Ambuja Exports Ltd.', value: 'GAEL.NS' },
	{ label: 'Gujarat Fluorochemicals Ltd.', value: 'FLUOROCHEM.NS' },
	{ label: 'Gujarat Gas Ltd.', value: 'GUJGASLTD.NS' },
	{ label: 'Gujarat Narmada Valley Fertilizers and Chemicals Ltd.', value: 'GNFC.NS' },
	{ label: 'Gujarat Pipavav Port Ltd.', value: 'GPPL.NS' },
	{ label: 'Gujarat State Fertilizers & Chemicals Ltd.', value: 'GSFC.NS' },
	{ label: 'Gujarat State Petronet Ltd.', value: 'GSPL.NS' },
	{ label: 'H.E.G. Ltd.', value: 'HEG.NS' },
	{ label: 'HCL Technologies Ltd.', value: 'HCLTECH.NS' },
	{ label: 'HDFC Asset Management Company Ltd.', value: 'HDFCAMC.NS' },
	{ label: 'HDFC Bank Ltd.', value: 'HDFCBANK.NS' },
	{ label: 'HDFC Life Insurance Company Ltd.', value: 'HDFCLIFE.NS' },
	{ label: 'HFCL Ltd.', value: 'HFCL.NS' },
	{ label: 'HLE Glascoat Ltd.', value: 'HLEGLAS.NS' },
	{ label: 'Happiest Minds Technologies Ltd.', value: 'HAPPSTMNDS.NS' },
	{ label: 'Hathway Cable & Datacom Ltd.', value: 'HATHWAY.NS' },
	{ label: 'Hatsun Agro Product Ltd.', value: 'HATSUN.NS' },
	{ label: 'Havells India Ltd.', value: 'HAVELLS.NS' },
	{ label: 'Hemisphere Properties India Ltd.', value: 'HEMIPROP.NS' },
	{ label: 'Hero MotoCorp Ltd.', value: 'HEROMOTOCO.NS' },
	{ label: 'Hikal Ltd.', value: 'HIKAL.NS' },
	{ label: 'Hindalco Industries Ltd.', value: 'HINDALCO.NS' },
	{ label: 'Hinduja Global Solutions Ltd.', value: 'HGS.NS' },
	{ label: 'Hindustan Aeronautics Ltd.', value: 'HAL.NS' },
	{ label: 'Hindustan Copper Ltd.', value: 'HINDCOPPER.NS' },
	{ label: 'Hindustan Petroleum Corporation Ltd.', value: 'HINDPETRO.NS' },
	{ label: 'Hindustan Unilever Ltd.', value: 'HINDUNILVR.NS' },
	{ label: 'Hindustan Zinc Ltd.', value: 'HINDZINC.NS' },
	{ label: 'Hitachi Energy India Ltd.', value: 'POWERINDIA.NS' },
	{ label: 'Home First Finance Company India Ltd.', value: 'HOMEFIRST.NS' },
	{ label: 'Honeywell Automation India Ltd.', value: 'HONAUT.NS' },
	{ label: 'Housing & Urban Development Corporation Ltd.', value: 'HUDCO.NS' },
	{ label: 'Housing Development Finance Corporation Ltd.', value: 'HDFC.NS' },
	{ label: 'ICICI Bank Ltd.', value: 'ICICIBANK.NS' },
	{ label: 'ICICI Lombard General Insurance Company Ltd.', value: 'ICICIGI.NS' },
	{ label: 'ICICI Prudential Life Insurance Company Ltd.', value: 'ICICIPRULI.NS' },
	{ label: 'ICICI Securities Ltd.', value: 'ISEC.NS' },
	{ label: 'IDBI Bank Ltd.', value: 'IDBI.NS' },
	{ label: 'IDFC First Bank Ltd.', value: 'IDFCFIRSTB.NS' },
	{ label: 'IDFC Ltd.', value: 'IDFC.NS' },
	{ label: 'IFB Industries Ltd.', value: 'IFBIND.NS' },
	{ label: 'IIFL Finance Ltd.', value: 'IIFL.NS' },
	{ label: 'IIFL Wealth Management Ltd.', value: 'IIFLWAM.NS' },
	{ label: 'IRB Infrastructure Developers Ltd.', value: 'IRB.NS' },
	{ label: 'IRCON International Ltd.', value: 'IRCON.NS' },
	{ label: 'ITC Ltd.', value: 'ITC.NS' },
	{ label: 'ITI Ltd.', value: 'ITI.NS' },
	{ label: 'India Cements Ltd.', value: 'INDIACEM.NS' },
	{ label: 'Indiabulls Housing Finance Ltd.', value: 'IBULHSGFIN.NS' },
	{ label: 'Indiabulls Real Estate Ltd.', value: 'IBREALEST.NS' },
	{ label: 'Indiamart Intermesh Ltd.', value: 'INDIAMART.NS' },
	{ label: 'Indian Bank', value: 'INDIANB.NS' },
	{ label: 'Indian Energy Exchange Ltd.', value: 'IEX.NS' },
	{ label: 'Indian Hotels Co. Ltd.', value: 'INDHOTEL.NS' },
	{ label: 'Indian Oil Corporation Ltd.', value: 'IOC.NS' },
	{ label: 'Indian Overseas Bank', value: 'IOB.NS' },
	{ label: 'Indian Railway Catering And Tourism Corporation Ltd.', value: 'IRCTC.NS' },
	{ label: 'Indian Railway Finance Corporation Ltd.', value: 'IRFC.NS' },
	{ label: 'Indigo Paints Ltd.', value: 'INDIGOPNTS.NS' },
	{ label: 'Indo Count Industries Ltd.', value: 'ICIL.NS' },
	{ label: 'Indoco Remedies Ltd.', value: 'INDOCO.NS' },
	{ label: 'Indraprastha Gas Ltd.', value: 'IGL.NS' },
	{ label: 'Indus Towers Ltd.', value: 'INDUSTOWER.NS' },
	{ label: 'IndusInd Bank Ltd.', value: 'INDUSINDBK.NS' },
	{ label: 'Infibeam Avenues Ltd.', value: 'INFIBEAM.NS' },
	{ label: 'Info Edge (India) Ltd.', value: 'NAUKRI.NS' },
	{ label: 'Infosys Ltd.', value: 'INFY.NS' },
	{ label: 'Inox Leisure Ltd.', value: 'INOXLEISUR.NS' },
	{ label: 'Intellect Design Arena Ltd.', value: 'INTELLECT.NS' },
	{ label: 'InterGlobe Aviation Ltd.', value: 'INDIGO.NS' },
	{ label: 'Ipca Laboratories Ltd.', value: 'IPCALAB.NS' },
	{ label: 'J.B. Chemicals & Pharmaceuticals Ltd.', value: 'JBCHEPHARM.NS' },
	{ label: 'J.K. Cement Ltd.', value: 'JKCEMENT.NS' },
	{ label: 'JK Lakshmi Cement Ltd.', value: 'JKLAKSHMI.NS' },
	{ label: 'JK Paper Ltd.', value: 'JKPAPER.NS' },
	{ label: 'JM Financial Ltd.', value: 'JMFINANCIL.NS' },
	{ label: 'JSW Energy Ltd.', value: 'JSWENERGY.NS' },
	{ label: 'JSW Steel Ltd.', value: 'JSWSTEEL.NS' },
	{ label: 'Jamna Auto Industries Ltd.', value: 'JAMNAAUTO.NS' },
	{ label: 'Jindal Stainless Ltd.', value: 'JSL.NS' },
	{ label: 'Jindal Steel & Power Ltd.', value: 'JINDALSTEL.NS' },
	{ label: 'Jubilant Foodworks Ltd.', value: 'JUBLFOOD.NS' },
	{ label: 'Jubilant Ingrevia Ltd.', value: 'JUBLINGREA.NS' },
	{ label: 'Jubilant Pharmova Ltd.', value: 'JUBLPHARMA.NS' },
	{ label: 'Justdial Ltd.', value: 'JUSTDIAL.NS' },
	{ label: 'Jyothy Labs Ltd.', value: 'JYOTHYLAB.NS' },
	{ label: 'K.P.R. Mill Ltd.', value: 'KPRMILL.NS' },
	{ label: 'KEI Industries Ltd.', value: 'KEI.NS' },
	{ label: 'KNR Constructions Ltd.', value: 'KNRCON.NS' },
	{ label: 'KPIT Technologies Ltd.', value: 'KPITTECH.NS' },
	{ label: 'KRBL Ltd.', value: 'KRBL.NS' },
	{ label: 'Kajaria Ceramics Ltd.', value: 'KAJARIACER.NS' },
	{ label: 'Kalpataru Power Transmission Ltd.', value: 'KALPATPOWR.NS' },
	{ label: 'Kalyan Jewellers India Ltd.', value: 'KALYANKJIL.NS' },
	{ label: 'Kansai Nerolac Paints Ltd.', value: 'KANSAINER.NS' },
	{ label: 'Karur Vysya Bank Ltd.', value: 'KARURVYSYA.NS' },
	{ label: 'Kec International Ltd.', value: 'KEC.NS' },
	{ label: 'Kotak Mahindra Bank Ltd.', value: 'KOTAKBANK.NS' },
	{ label: 'Krishna Institute of Medical Sciences Ltd.', value: 'KIMS.NS' },
	{ label: 'L&T Finance Holdings Ltd.', value: 'L&TFH.NS' },
	{ label: 'L&T Technology Services Ltd.', value: 'LTTS.NS' },
	{ label: 'LIC Housing Finance Ltd.', value: 'LICHSGFIN.NS' },
	{ label: 'Lakshmi Machine Works Ltd.', value: 'LAXMIMACH.NS' },
	{ label: 'Larsen & Toubro Infotech Ltd.', value: 'LTI.NS' },
	{ label: 'Larsen & Toubro Ltd.', value: 'LT.NS' },
	{ label: 'Latent View Analytics Ltd.', value: 'LATENTVIEW.NS' },
	{ label: 'Laurus Labs Ltd.', value: 'LAURUSLABS.NS' },
	{ label: 'Laxmi Organic Industries Ltd.', value: 'LXCHEM.NS' },
	{ label: 'Life Insurance Corporation of India', value: 'LICI.NS' },
	{ label: 'Linde India Ltd.', value: 'LINDEINDIA.NS' },
	{ label: 'Lupin Ltd.', value: 'LUPIN.NS' },
	{ label: 'Lux Industries Ltd.', value: 'LUXIND.NS' },
	{ label: 'MMTC Ltd.', value: 'MMTC.NS' },
	{ label: 'MOIL Ltd.', value: 'MOIL.NS' },
	{ label: 'MRF Ltd.', value: 'MRF.NS' },
	{ label: 'MTAR Technologies Ltd.', value: 'MTARTECH.NS' },
	{ label: 'Macrotech Developers Ltd.', value: 'LODHA.NS' },
	{ label: 'Mahanagar Gas Ltd.', value: 'MGL.NS' },
	{ label: 'Mahindra & Mahindra Financial Services Ltd.', value: 'M&MFIN.NS' },
	{ label: 'Mahindra & Mahindra Ltd.', value: 'M&M.NS' },
	{ label: 'Mahindra CIE Automotive Ltd.', value: 'MAHINDCIE.NS' },
	{ label: 'Mahindra Holidays & Resorts India Ltd.', value: 'MHRIL.NS' },
	{ label: 'Mahindra Logistics Ltd.', value: 'MAHLOG.NS' },
	{ label: 'Manappuram Finance Ltd.', value: 'MANAPPURAM.NS' },
	{ label: 'Mangalore Refinery & Petrochemicals Ltd.', value: 'MRPL.NS' },
	{ label: 'Marico Ltd.', value: 'MARICO.NS' },
	{ label: 'Maruti Suzuki India Ltd.', value: 'MARUTI.NS' },
	{ label: 'Mastek Ltd.', value: 'MASTEK.NS' },
	{ label: 'Max Financial Services Ltd.', value: 'MFSL.NS' },
	{ label: 'Max Healthcare Institute Ltd.', value: 'MAXHEALTH.NS' },
	{ label: 'Mazagoan Dock Shipbuilders Ltd.', value: 'MAZDOCK.NS' },
	{ label: 'Medplus Health Services Ltd.', value: 'MEDPLUS.NS' },
	{ label: 'Metro Brands Ltd.', value: 'METROBRAND.NS' },
	{ label: 'Metropolis Healthcare Ltd.', value: 'METROPOLIS.NS' },
	{ label: 'MindTree Ltd.', value: 'MINDTREE.NS' },
	{ label: 'Motilal Oswal Financial Services Ltd.', value: 'MOTILALOFS.NS' },
	{ label: 'MphasiS Ltd.', value: 'MPHASIS.NS' },
	{ label: 'Multi Commodity Exchange of India Ltd.', value: 'MCX.NS' },
	{ label: 'Muthoot Finance Ltd.', value: 'MUTHOOTFIN.NS' },
	{ label: 'NATCO Pharma Ltd.', value: 'NATCOPHARM.NS' },
	{ label: 'NBCC (India) Ltd.', value: 'NBCC.NS' },
	{ label: 'NCC Ltd.', value: 'NCC.NS' },
	{ label: 'NESCO Ltd.', value: 'NESCO.NS' },
	{ label: 'NHPC Ltd.', value: 'NHPC.NS' },
	{ label: 'NLC India Ltd.', value: 'NLCINDIA.NS' },
	{ label: 'NOCIL Ltd.', value: 'NOCIL.NS' },
	{ label: 'NTPC Ltd.', value: 'NTPC.NS' },
	{ label: 'Narayana Hrudayalaya Ltd.', value: 'NH.NS' },
	{ label: 'National Aluminium Co. Ltd.', value: 'NATIONALUM.NS' },
	{ label: 'Navin Fluorine International Ltd.', value: 'NAVINFLUOR.NS' },
	{ label: 'Nazara Technologies Ltd.', value: 'NAZARA.NS' },
	{ label: 'Nestle India Ltd.', value: 'NESTLEIND.NS' },
	{ label: 'Network18 Media & Investments Ltd.', value: 'NETWORK18.NS' },
	{ label: 'Nippon Life India Asset Management Ltd.', value: 'NAM-INDIA.NS' },
	{ label: 'Nuvoco Vistas Corporation Ltd.', value: 'NUVOCO.NS' },
	{ label: 'Oberoi Realty Ltd.', value: 'OBEROIRLTY.NS' },
	{ label: 'Oil & Natural Gas Corporation Ltd.', value: 'ONGC.NS' },
	{ label: 'Oil India Ltd.', value: 'OIL.NS' },
	{ label: 'One 97 Communications Ltd.', value: 'PAYTM.NS' },
	{ label: 'Oracle Financial Services Software Ltd.', value: 'OFSS.NS' },
	{ label: 'Orient Electric Ltd.', value: 'ORIENTELEC.NS' },
	{ label: 'PB Fintech Ltd.', value: 'POLICYBZR.NS' },
	{ label: 'PCBL Ltd.', value: 'PCBL.NS' },
	{ label: 'PI Industries Ltd.', value: 'PIIND.NS' },
	{ label: 'PNB Housing Finance Ltd.', value: 'PNBHOUSING.NS' },
	{ label: 'PNC Infratech Ltd.', value: 'PNCINFRA.NS' },
	{ label: 'PVR Ltd.', value: 'PVR.NS' },
	{ label: 'Page Industries Ltd.', value: 'PAGEIND.NS' },
	{ label: 'Persistent Systems Ltd.', value: 'PERSISTENT.NS' },
	{ label: 'Petronet LNG Ltd.', value: 'PETRONET.NS' },
	{ label: 'Pfizer Ltd.', value: 'PFIZER.NS' },
	{ label: 'Phoenix Mills Ltd.', value: 'PHOENIXLTD.NS' },
	{ label: 'Pidilite Industries Ltd.', value: 'PIDILITIND.NS' },
	{ label: 'Poly Medicure Ltd.', value: 'POLYMED.NS' },
	{ label: 'Polycab India Ltd.', value: 'POLYCAB.NS' },
	{ label: 'Polyplex Corporation Ltd.', value: 'POLYPLEX.NS' },
	{ label: 'Poonawalla Fincorp Ltd.', value: 'POONAWALLA.NS' },
	{ label: 'Power Finance Corporation Ltd.', value: 'PFC.NS' },
	{ label: 'Power Grid Corporation of India Ltd.', value: 'POWERGRID.NS' },
	{ label: 'Praj Industries Ltd.', value: 'PRAJIND.NS' },
	{ label: 'Prestige Estates Projects Ltd.', value: 'PRESTIGE.NS' },
	{ label: 'Prince Pipes and Fittings Ltd.', value: 'PRINCEPIPE.NS' },
	{ label: 'Prism Johnson Ltd.', value: 'PRSMJOHNSN.NS' },
	{ label: 'Privi Speciality Chemicals Ltd.', value: 'PRIVISCL.NS' },
	{ label: 'Procter & Gamble Health Ltd.', value: 'PGHL.NS' },
	{ label: 'Procter & Gamble Hygiene & Health Care Ltd.', value: 'PGHH.NS' },
	{ label: 'Punjab National Bank', value: 'PNB.NS' },
	{ label: 'Quess Corp Ltd.', value: 'QUESS.NS' },
	{ label: 'RBL Bank Ltd.', value: 'RBLBANK.NS' },
	{ label: 'REC Ltd.', value: 'RECLTD.NS' },
	{ label: 'RHI MAGNESITA INDIA LTD.', value: 'RHIM.NS' },
	{ label: 'RITES Ltd.', value: 'RITES.NS' },
	{ label: 'Radico Khaitan Ltd', value: 'RADICO.NS' },
	{ label: 'Rail Vikas Nigam Ltd.', value: 'RVNL.NS' },
	{ label: 'Railtel Corporation Of India Ltd.', value: 'RAILTEL.NS' },
	{ label: 'Rain Industries Ltd', value: 'RAIN.NS' },
	{ label: 'Rajesh Exports Ltd.', value: 'RAJESHEXPO.NS' },
	{ label: 'Rallis India Ltd.', value: 'RALLIS.NS' },
	{ label: 'Rashtriya Chemicals & Fertilizers Ltd.', value: 'RCF.NS' },
	{ label: 'Ratnamani Metals & Tubes Ltd.', value: 'RATNAMANI.NS' },
	{ label: 'RattanIndia Enterprises Ltd.', value: 'RTNINDIA.NS' },
	{ label: 'Redington (India) Ltd.', value: 'REDINGTON.NS' },
	{ label: 'Relaxo Footwears Ltd.', value: 'RELAXO.NS' },
	{ label: 'Reliance Industries Ltd.', value: 'RELIANCE.NS' },
	{ label: 'Restaurant Brands Asia Ltd.', value: 'RBA.NS' },
	{ label: 'Rossari Biotech Ltd.', value: 'ROSSARI.NS' },
	{ label: 'Route Mobile Ltd.', value: 'ROUTE.NS' },
	{ label: 'SBI Cards and Payment Services Ltd.', value: 'SBICARD.NS' },
	{ label: 'SBI Life Insurance Company Ltd.', value: 'SBILIFE.NS' },
	{ label: 'SIS Ltd.', value: 'SIS.NS' },
	{ label: 'SJVN Ltd.', value: 'SJVN.NS' },
	{ label: 'SKF India Ltd.', value: 'SKFINDIA.NS' },
	{ label: 'SRF Ltd.', value: 'SRF.NS' },
	{ label: 'Sanofi India Ltd.', value: 'SANOFI.NS' },
	{ label: 'Sapphire Foods India Ltd.', value: 'SAPPHIRE.NS' },
	{ label: 'Saregama India Ltd', value: 'SAREGAMA.NS' },
	{ label: 'Schaeffler India Ltd.', value: 'SCHAEFFLER.NS' },
	{ label: 'Sequent Scientific Ltd.', value: 'SEQUENT.NS' },
	{ label: 'Sheela Foam Ltd.', value: 'SFL.NS' },
	{ label: 'Shilpa Medicare Ltd.', value: 'SHILPAMED.NS' },
	{ label: 'Shipping Corporation of India Ltd.', value: 'SCI.NS' },
	{ label: 'Shree Cement Ltd.', value: 'SHREECEM.NS' },
	{ label: 'Shree Renuka Sugars Ltd.', value: 'RENUKA.NS' },
	{ label: 'Shriram Transport Finance Co. Ltd.', value: 'SRTRANSFIN.NS' },
	{ label: 'Shyam Metalics and Energy Ltd.', value: 'SHYAMMETL.NS' },
	{ label: 'Siemens Ltd.', value: 'SIEMENS.NS' },
	{ label: 'Sobha Ltd.', value: 'SOBHA.NS' },
	{ label: 'Solar Industries India Ltd.', value: 'SOLARINDS.NS' },
	{ label: 'Solara Active Pharma Sciences Ltd.', value: 'SOLARA.NS' },
	{ label: 'Sona BLW Precision Forgings Ltd.', value: 'SONACOMS.NS' },
	{ label: 'Sonata Software Ltd.', value: 'SONATSOFTW.NS' },
	{ label: 'Spicejet Ltd.', value: 'SPICEJET.NS' },
	{ label: 'Star Health and Allied Insurance Company Ltd.', value: 'STARHEALTH.NS' },
	{ label: 'State Bank of India', value: 'SBIN.NS' },
	{ label: 'Steel Authority of India Ltd.', value: 'SAIL.NS' },
	{ label: 'Sterling and Wilson Renewable Energy Ltd.', value: 'SWSOLAR.NS' },
	{ label: 'Sterlite Technologies Ltd.', value: 'STLTECH.NS' },
	{ label: 'Strides Pharma Science Ltd.', value: 'STAR.NS' },
	{ label: 'Sudarshan Chemical Industries Ltd.', value: 'SUDARSCHEM.NS' },
	{ label: 'Sumitomo Chemical India Ltd.', value: 'SUMICHEM.NS' },
	{ label: 'Sun Pharma Advanced Research Company Ltd.', value: 'SPARC.NS' },
	{ label: 'Sun Pharmaceutical Industries Ltd.', value: 'SUNPHARMA.NS' },
	{ label: 'Sun TV Network Ltd.', value: 'SUNTV.NS' },
	{ label: 'Sundaram Finance Ltd.', value: 'SUNDARMFIN.NS' },
	{ label: 'Sundram Fasteners Ltd.', value: 'SUNDRMFAST.NS' },
	{ label: 'Sunteck Realty Ltd.', value: 'SUNTECK.NS' },
	{ label: 'Suprajit Engineering Ltd.', value: 'SUPRAJIT.NS' },
	{ label: 'Supreme Industries Ltd.', value: 'SUPREMEIND.NS' },
	{ label: 'Suven Pharmaceuticals Ltd.', value: 'SUVENPHAR.NS' },
	{ label: 'Suzlon Energy Ltd.', value: 'SUZLON.NS' },
	{ label: 'Symphony Ltd.', value: 'SYMPHONY.NS' },
	{ label: 'Syngene International Ltd.', value: 'SYNGENE.NS' },
	{ label: 'TCI Express Ltd.', value: 'TCIEXP.NS' },
	{ label: 'TCNS Clothing Co. Ltd.', value: 'TCNSBRANDS.NS' },
	{ label: 'TTK Prestige Ltd.', value: 'TTKPRESTIG.NS' },
	{ label: 'TV18 Broadcast Ltd.', value: 'TV18BRDCST.NS' },
	{ label: 'TVS Motor Company Ltd.', value: 'TVSMOTOR.NS' },
	{ label: 'Tanla Platforms Ltd.', value: 'TANLA.NS' },
	{ label: 'Tata Chemicals Ltd.', value: 'TATACHEM.NS' },
	{ label: 'Tata Coffee Ltd.', value: 'TATACOFFEE.NS' },
	{ label: 'Tata Communications Ltd.', value: 'TATACOMM.NS' },
	{ label: 'Tata Consultancy Services Ltd.', value: 'TCS.NS' },
	{ label: 'Tata Consumer Products Ltd.', value: 'TATACONSUM.NS' },
	{ label: 'Tata Elxsi Ltd.', value: 'TATAELXSI.NS' },
	{ label: 'Tata Investment Corporation Ltd.', value: 'TATAINVEST.NS' },
	{ label: 'Tata Motors Ltd DVR', value: 'TATAMTRDVR.NS' },
	{ label: 'Tata Motors Ltd.', value: 'TATAMOTORS.NS' },
	{ label: 'Tata Power Co. Ltd.', value: 'TATAPOWER.NS' },
	{ label: 'Tata Steel Long Products Ltd.', value: 'TATASTLLP.NS' },
	{ label: 'Tata Steel Ltd.', value: 'TATASTEEL.NS' },
	{ label: 'Tata Teleservices (Maharashtra) Ltd.', value: 'TTML.NS' },
	{ label: 'Teamlease Services Ltd.', value: 'TEAMLEASE.NS' },
	{ label: 'Tech Mahindra Ltd.', value: 'TECHM.NS' },
	{ label: 'The New India Assurance Company Ltd.', value: 'NIACL.NS' },
	{ label: 'The Ramco Cements Ltd.', value: 'RAMCOCEM.NS' },
	{ label: 'Thermax Ltd.', value: 'THERMAX.NS' },
	{ label: 'Thyrocare Technologies Ltd.', value: 'THYROCARE.NS' },
	{ label: 'Timken India Ltd.', value: 'TIMKEN.NS' },
	{ label: 'Titan Company Ltd.', value: 'TITAN.NS' },
	{ label: 'Torrent Pharmaceuticals Ltd.', value: 'TORNTPHARM.NS' },
	{ label: 'Torrent Power Ltd.', value: 'TORNTPOWER.NS' },
	{ label: 'Trent Ltd.', value: 'TRENT.NS' },
	{ label: 'Trident Ltd.', value: 'TRIDENT.NS' },
	{ label: 'Triveni Engineering & Industries Ltd.', value: 'TRIVENI.NS' },
	{ label: 'Triveni Turbine Ltd.', value: 'TRITURBINE.NS' },
	{ label: 'Tube Investments of India Ltd.', value: 'TIINDIA.NS' },
	{ label: 'UCO Bank', value: 'UCOBANK.NS' },
	{ label: 'UFLEX Ltd.', value: 'UFLEX.NS' },
	{ label: 'UNO Minda Ltd.', value: 'UNOMINDA.NS' },
	{ label: 'UPL Ltd.', value: 'UPL.NS' },
	{ label: 'UTI Asset Management Company Ltd.', value: 'UTIAMC.NS' },
	{ label: 'UltraTech Cement Ltd.', value: 'ULTRACEMCO.NS' },
	{ label: 'Union Bank of India', value: 'UNIONBANK.NS' },
	{ label: 'United Breweries Ltd.', value: 'UBL.NS' },
	{ label: 'United Spirits Ltd.', value: 'MCDOWELL-N.NS' },
	{ label: 'V-Guard Industries Ltd.', value: 'VGUARD.NS' },
	{ label: 'V-Mart Retail Ltd.', value: 'VMART.NS' },
	{ label: 'V.I.P. Industries Ltd.', value: 'VIPIND.NS' },
	{ label: 'Vaibhav Global Ltd.', value: 'VAIBHAVGBL.NS' },
	{ label: 'Vakrangee Ltd.', value: 'VAKRANGEE.NS' },
	{ label: 'Vardhman Textiles Ltd.', value: 'VTL.NS' },
	{ label: 'Varroc Engineering Ltd.', value: 'VARROC.NS' },
	{ label: 'Varun Beverages Ltd.', value: 'VBL.NS' },
	{ label: 'Vedanta Ltd.', value: 'VEDL.NS' },
	{ label: "Venky's (India) Ltd.", value: 'VENKEYS.NS' },
	{ label: 'Vijaya Diagnostic Centre Ltd.', value: 'VIJAYA.NS' },
	{ label: 'Vinati Organics Ltd.', value: 'VINATIORGA.NS' },
	{ label: 'Vodafone Idea Ltd.', value: 'IDEA.NS' },
	{ label: 'Voltas Ltd.', value: 'VOLTAS.NS' },
	{ label: 'Welspun Corp Ltd.', value: 'WELCORP.NS' },
	{ label: 'Welspun India Ltd.', value: 'WELSPUNIND.NS' },
	{ label: 'Westlife Development Ltd.', value: 'WESTLIFE.NS' },
	{ label: 'Whirlpool of India Ltd.', value: 'WHIRLPOOL.NS' },
	{ label: 'Wipro Ltd.', value: 'WIPRO.NS' },
	{ label: 'Wockhardt Ltd.', value: 'WOCKPHARMA.NS' },
	{ label: 'Yes Bank Ltd.', value: 'YESBANK.NS' },
	{ label: 'ZF Commercial Vehicle Control Systems India Ltd.', value: 'ZFCVINDIA.NS' },
	{ label: 'Zee Entertainment Enterprises Ltd.', value: 'ZEEL.NS' },
	{ label: 'Zensar Technolgies Ltd.', value: 'ZENSARTECH.NS' },
	{ label: 'Zomato Ltd.', value: 'ZOMATO.NS' },
	{ label: 'Zydus Lifesciences Ltd.', value: 'ZYDUSLIFE.NS' },
	{ label: 'Zydus Wellness Ltd.', value: 'ZYDUSWELL.NS' },
	{ label: 'eClerx Services Ltd.', value: 'ECLERX.NS' },
];
